// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZXWZTZH9gXL6RPfM3Oda894p1Aangrhg',
    appId: '1:3814365939:web:8a063337557d41e89a3586',
    messagingSenderId: '3814365939',
    projectId: 'fir-practice-dfdac',
    authDomain: 'fir-practice-dfdac.firebaseapp.com',
    storageBucket: 'fir-practice-dfdac.firebasestorage.app',
    measurementId: 'G-VDTPG542NY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2sGs12dbN4wjgOmC0-lPO7lcc3LvKb9E',
    appId: '1:3814365939:android:09e6b85e0bf95dfb9a3586',
    messagingSenderId: '3814365939',
    projectId: 'fir-practice-dfdac',
    storageBucket: 'fir-practice-dfdac.firebasestorage.app',
  );
}
